### ISSUE TITLE
Could We Get A Newer Version Of NoVNC Becuase It Doesn't Scale

### ISSUE THREAD

**Issue by MapGuy11** [solarkennedy/wine-x11-novnc-docker#8]
This really isn't a issue I love your docker image I just wish we could get a newer NoVNC package since it doesn't scale at all to your browser window it just stays at a small 4:3 aspect ratio. Also Newer version of NoVNC have more options ,but overall your package is great!

**Comment by nsapa** [comment]
Hi,

The docker image is running the latest stable version of NoVNC with the vnc_lite.html template.
That's why they are very little options. Change the script to use vnc.html instead and you will get the full featured GUI.
The 4:3 aspect ratio come from the Xvfb resolution defined [in supervisord.conf](https://github.com/solarkennedy/wine-x11-novnc-docker/blob/c39e83d744eb989ce6c851f46b86a50c1b98ac75/supervisord.conf#L5).

Best regards,
NS

**Comment by bkjaya2020** [comment]
Hi Nicolas
This is to inform you that  I have used solarkeneddy/wine-x11-novnc-docker to build SMath Studio-0.99.7030 docker image .
https://github.com/bkjaya2020/smathstudio
I have posted this comment here as there is no other way to communicate with you .
Thank you very much 
Best regards
B.K.Jayasundera

**Comment by solarkennedy** [comment]
Thanks @bkjaya2020 :+1:, looks awesome!

**Comment by bkjaya2020** [comment]
Thank you Kyle

**Comment by bkjaya2020** [comment]
Hi Kyle,
I have used your wonderful creation "solarkennedy/wine-x11-novnc-docker" again . Please refer the following link .
https://github.com/bkjaya2020/jmcad-pre-installed-docker
Thank you.
Best regards,
B.K.Jayasundera

**Comment by MapGuy11** [comment]
Is it ok if I close this?
